# Docker Compose para debug do problema de entrypoint
# Use este arquivo para testar se o problema persiste

services:
  moburb-app-debug:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moburb-debug
    restart: "no"  # Não reinicia para facilitar debug
    # TESTE 1: Comando mais simples possível
    command: ["npm", "start"]
    ports:
      - "3501:3500"  # Porta diferente para não conflitar
    environment:
      - NODE_ENV=production
      - PORT=3500
      - HOSTNAME=0.0.0.0
      - ENVIRONMENT=production
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - /usr/sbin/sendmail:/usr/sbin/sendmail:ro
      - /etc/mail:/etc/mail:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    # Remove healthcheck para debug
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3500/api/health"]

  # Versão ainda mais simples para teste
  moburb-app-minimal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moburb-minimal
    restart: "no"
    # TESTE 2: Apenas shell simples
    command: ["sh", "-c", "echo 'Container iniciado' && sleep 3600"]
    environment:
      - NODE_ENV=production
    network_mode: host
