# Docker Compose alternativo para CentOS 7
# Usa Dockerfile.centos7 com imagem base node:20-slim

services:
  moburb-app:
    build:
      context: .
      dockerfile: Dockerfile.centos7  # Usa Dockerfile alternativo
    container_name: moburb-concurso-centos7
    restart: unless-stopped
    # Comando simplificado que deve funcionar
    command: ["sh", "-c", "sleep 15 && npx prisma migrate deploy && npx prisma generate && npm run seed || echo 'Seed executado' && npm start"]
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=production
      - PORT=3500
      - HOSTNAME=0.0.0.0
      - ENVIRONMENT=production
    env_file:
      - .env.production
    volumes:
      # Volume para uploads persistentes
      - ./uploads:/app/uploads
      # Volume para logs
      - ./logs:/app/logs
      # Compartilha o sendmail do host (modo específico)
      - /usr/sbin/sendmail:/usr/sbin/sendmail:ro
      - /usr/lib/sendmail:/usr/lib/sendmail:ro
      # Compartilha configurações de mail do sistema
      - /etc/mail:/etc/mail:ro
      # Bibliotecas necessárias para sendmail
      - /lib64:/lib64:ro
      - /usr/lib64:/usr/lib64:ro
      # Timezone do sistema
      - /etc/localtime:/etc/localtime:ro
    # Conecta com a rede do host para acessar MySQL local e sendmail
    network_mode: host
    depends_on: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3500/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Mais tempo para inicialização

# Usando network_mode: host, não precisa definir networks customizadas
